### ISSUE TITLE
URL generation given routing function and parameters.

### ISSUE THREAD

**Issue by meric** [elierotenberg/isomorphic-router#1]
Instead of having to write `"/users/" + userId`, is there a way to generate the url using:

`getUrl(viewUser, {user: userId})`, and returning a generated URL that could be used in a `<a/>` element?

It would reduce the work required when urls have to be modified in the application. No need to go to each link and change it.

**Comment by elierotenberg** [comment]
In my apps I simply use a static Object acting as an URL template map, eg.

``` js
const urls = {
  viewUser({ user }) {
    return `/users/${user.userId}`;
  }
}
```
